/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Breadcrumbs: typeof import('./components/Breadcrumbs/index.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog/index.vue')['default']
    'ConfirmDialog copy': typeof import('./components/ConfirmDialog copy.vue')['default']
    copy: typeof import('./components/ConfirmDialog copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
